from enum import Enum


class Discounts:
    PRODUCT_DISCOUNT_PERCENT = 10.0
    SERVICE_DISCOUNT_FOR_PREMIUM_PERCENT = 20.0
    SERVICE_DISCOUNT_FOR_GOLD_PERCENT = 15.0
    SERVICE_DISCOUNT_FOR_SILVER_PERCENT = 10.0
    NEW_CUSTOMER_GIFT_AMOUNT = 20.0
    OLD_CUSTOMER_GIFT_AMOUNT = 0.0
